//
//  Copyright 2026 Readium Foundation. All rights reserved.
//  Use of this source code is governed by the BSD-style license
//  available in the top-level LICENSE file of the project.
//

import Foundation
import ReadiumShared

/// Receives high-level playback events from an ``GuidedAudioNavigator``.
@MainActor public protocol GuidedAudioNavigatorDelegate: AnyObject {
    /// Called when the navigator's playback status changes.
    func navigator(_ navigator: GuidedAudioNavigator, didChangeStatus status: PlaybackStatus)

    /// Called when an unrecoverable error occurs.
    ///
    /// The navigator transitions to ``PlaybackStatus/paused`` status. The
    /// delegate should surface the error to the user and may attempt to resume.
    func navigator(_ navigator: GuidedAudioNavigator, didFailWithError error: Error)
}

/// The playback state of a ``GuidedAudioNavigator``.
public enum PlaybackStatus: Hashable {
    /// The navigator is initialized and waiting for the first `play()`
    /// call which will start from the beginning of the publication.
    case idle

    /// Playback is paused.
    ///
    /// `play()` will resume playback from the current position.
    case paused

    /// The navigator intends to play but is waiting for audio data to load or
    /// buffer.
    case loading

    /// The navigator is actively playing audio.
    case playing

    /// The last audio clip ended naturally and there is no next clip.
    ///
    /// Calling `play()` will restart from the beginning of the publication.
    case finished
}

/// Plays audio clips from a Publication's Guided Navigation.
@MainActor public final class GuidedAudioNavigator: Loggable {
    /// Event callbacks for the navigator.
    public weak var delegate: (any GuidedAudioNavigatorDelegate)?

    private let publication: Publication

    /// Sequences the stream of ``GuidedNavigationNode`` into coalesced
    /// ``GuidedAudioClip`` ready for the `player`.
    private let sequencer: GuidedAudioSequencer

    /// Renders ``GuidedAudioClip`` items.
    private let player: AudioClipPlayer

    /// Current playback status.
    public var status: PlaybackStatus {
        switch state {
        case .idle: .idle
        case .paused: .paused
        case .loading: .loading
        case .playing: .playing
        case .finished: .finished
        }
    }

    private var state: State = .idle {
        didSet {
            delegate?.navigator(self, didChangeStatus: status)
        }
    }

    private enum State {
        /// The navigator is initialized and waiting for the first `play()`
        /// call which will start from the beginning of the publication.
        case idle

        /// Playback is paused.
        ///
        /// `play()` will resume playback from the current position.
        case paused(ClipInfo)

        /// The navigator intends to play but is waiting for audio data to load
        /// or buffer.
        case loading(ClipInfo)

        /// The navigator is actively playing audio.
        case playing(ClipInfo)

        /// The last audio clip ended naturally and there is no next clip.
        ///
        /// Calling `play()` will restart from the beginning of the publication.
        case finished

        /// Returns the `ClipInfo` associated to the current state, if any.
        var clip: ClipInfo? {
            switch self {
            case .idle, .finished: nil
            case let .paused(clip), let .loading(clip), let .playing(clip): clip
            }
        }

        /// Updates the state by modifing the current `clip`.
        mutating func editClip(_ transform: (inout ClipInfo) throws -> Void) rethrows {
            switch self {
            case .idle, .finished: break

            case var .paused(clip):
                try transform(&clip)
                self = .paused(clip)

            case var .loading(clip):
                try transform(&clip)
                self = .loading(clip)

            case var .playing(clip):
                try transform(&clip)
                self = .playing(clip)
            }
        }
    }

    private struct ClipInfo {
        /// Actual clip generated by the `GuidedAudioSequencer`.
        let clip: GuidedAudioClip

        /// Index of the current node/segment within `clip`.
        var nodeIndex: Int

        /// Precomputed prefix sums of segment durations for `clip`.
        /// `cumulativeElapsed[i]` is the total playback time before
        /// segment `i`.
        let cumulativeElapsed: [TimeInterval]

        /// Returns the total duration of this clip.
        ///
        /// - Parameter playerDuration: Duration reported by the `player` for
        ///   the whole file.
        func duration(playerDuration: TimeInterval?) -> TimeInterval? {
            clip.clip.duration(fileDuration: playerDuration)
        }

        /// Returns the current time in the `clip`, taking into account only
        /// the declared segments.
        ///
        /// - Parameter playerTime: Current time in the `player`.
        func time(playerTime: TimeInterval) -> TimeInterval? {
            (cumulativeElapsed.getOrNil(nodeIndex) ?? 0)
                + max(0, playerTime - clip.clip.segments[nodeIndex].start)
        }
    }

    public init?(
        publication: Publication,
        readingOrder: [AnyURL]? = nil
    ) {
        guard let cursor = GuidedNavigationCursor(publication: publication, readingOrder: readingOrder) else {
            return nil
        }

        self.publication = publication
        sequencer = GuidedAudioSequencer(
            publication: publication,
            cursor: cursor,
            skippedRoles: [.bubble]
        )
        player = AudioClipPlayer()
        player.delegate = self
    }

    // MARK: - Time

    /// The reference frame for a time or duration query.
    public enum TimeScope {
        /// Relative to the whole publication.
        case publication

        /// Relative to the currently playing audio resource.
        case resource
    }

    /// Returns the current playback position within `scope`, in seconds, or
    /// `nil` if no item is currently active or the time for the requested scope
    /// cannot be determined.
    public func time(in scope: TimeScope) -> TimeInterval? {
        switch scope {
        case .resource:
            return state.clip?.time(playerTime: player.time)
        case .publication:
            return nil
        }
    }

    /// Returns the total duration of `scope` in seconds, or `nil` if it is not
    /// yet known, or the duration for the requested scope cannot be determined.
    public func duration(of scope: TimeScope) -> TimeInterval? {
        switch scope {
        case .resource:
            return state.clip?.duration(playerDuration: player.duration)
        case .publication:
            return publication.metadata.duration
        }
    }

    /// Registers a block to be called at regular intervals while playing.
    ///
    /// - Parameters:
    ///   - interval: How often to fire the block, in seconds. Defaults to 0.5.
    ///   - block: Receives the navigator so callers can read `time(in:)` and
    ///     `duration(of:)`. Only fires when the narrator that ticked is the
    ///     active narrator.
    /// - Returns: An opaque token that must be retained for as long as the
    ///   observation should remain active. Releasing the token cancels the
    ///   observer.
    public func addPeriodicTimeObserver(
        forInterval interval: TimeInterval = 0.5,
        using block: @escaping (GuidedAudioNavigator) -> Void
    ) -> Any {
        player.addPeriodicTimeObserver(forInterval: interval) { [weak self] in
            guard let self else { return }
            block(self)
        }
    }

    // MARK: - Playback control

    /// Starts or resumes the playback.
    ///
    /// If not already started, begins playing from the start of the
    /// publication.
    public func play() {
        log(.debug, "play()")
        Task {
            switch state {
            case .idle, .finished:
                await skipToNextAudioClip()
            case .paused:
                player.resume()
            case .loading, .playing:
                break
            }
        }
    }

    /// Begins playback from the given location in the publication's reading
    /// order.
    public func play(from location: any ReferenceLocation) {
        Task {
            log(.debug, "play(from:) location=\(location)")

            guard
                let ref = location.reference,
                let (clip, startIndex) = await sequencer.seek(to: ref)
            else {
                log(.warning, "play(from:): could not seek to location \(location)")
                return
            }

            play(clip, startAt: startIndex)
        }
    }

    /// Pauses the playback. Has no effect when already paused or idle.
    public func pause() {
        switch state {
        case .idle, .finished, .paused:
            break
        case .loading, .playing:
            player.pause()
        }
    }

    /// Skips to the next audio segment.
    public func skipForward() {
        Task {
            if !player.skipToNextSegment() {
                await skipToNextAudioClip()
            } else {
                log(.debug, "goForward(): skipped to next segment")
            }
        }
    }

    /// Skips to the previous audio segment.
    public func skipBackward() {
        Task {
            if !player.skipToPreviousSegment() {
                await skipToPreviousAudioClip(fromEnd: true)
            } else {
                log(.debug, "goBackward(): skipped to previous segment")
            }
        }
    }

    /// Skips to the first segment of the next reading order resource.
    public func skipToNextResource() {
        Task {
            await skipToNextAudioClip()
        }
    }

    /// Skips to the first segment of the previous reading order resource.
    public func skipToPreviousResource() {
        Task {
            await skipToPreviousAudioClip(fromEnd: false)
        }
    }

    private func skipToNextAudioClip() async {
        guard let clip = await sequencer.next() else {
            log(.debug, "goForward(): reached end of publication")
            player.stop()
            state = .finished
            return
        }

        log(.debug, "goForward(): loading next clip \(clip.clip.link.href)")
        play(clip, startAt: 0)
    }

    /// - Parameter fromEnd: Indicates if we should start the playback from the
    ///   end of the clip or the start. When skipping backward we want to start
    ///   from the last node.
    private func skipToPreviousAudioClip(fromEnd: Bool) async {
        guard let clip = await sequencer.previous() else {
            log(.debug, "goBackward(): reached beginning of publication")
            return
        }

        log(.debug, "goBackward(): loading previous clip \(clip.clip.link.href)")
        play(clip, startAt: fromEnd ? clip.nodes.count - 1 : 0)
    }

    /// Loads and starts playing `guidedClip` from the given segment `index`.
    private func play(_ guidedClip: GuidedAudioClip, startAt index: Int) {
        state = .playing(ClipInfo(
            clip: guidedClip,
            nodeIndex: index,
            cumulativeElapsed: guidedClip.clip.computeCumulativeElapsed()
        ))

        player.play(guidedClip.clip, startAt: index)
    }
}

extension GuidedAudioNavigator: AudioClipPlayerDelegate {
    public func audioClipPlayer(_ player: AudioClipPlayer, resourceFor link: Link) throws -> any Resource {
        guard let resource = publication.get(link) else {
            throw DebugError("Requested link was not found in the publication: \(link.href)")
        }
        return resource
    }

    public func audioClipPlayer(_ player: AudioClipPlayer, willStartSegmentAt index: Int, in clip: AudioClip) {
        log(.debug, "willStartSegmentAt \(index)/\(clip.segments.count - 1) in \(clip.link.href)")
        state.editClip {
            $0.nodeIndex = index
        }
    }

    public func audioClipPlayer(_ player: AudioClipPlayer, didFinishSegmentAt index: Int, in clip: AudioClip) {
        log(.debug, "didFinishSegmentAt \(index)/\(clip.segments.count - 1) in \(clip.link.href)")
    }

    public func audioClipPlayer(_ player: AudioClipPlayer, didFinishPlaying clip: AudioClip) {
        log(.debug, "didFinishPlaying \(clip.link.href)")
        Task {
            await skipToNextAudioClip()
        }
    }

    public func audioClipPlayer(_ player: AudioClipPlayer, didChangeStatus playerStatus: AudioClipPlayerStatus) {
        log(.debug, "audioClipPlayer didChangeStatus \(playerStatus)")

        guard let clip = state.clip else {
            return
        }

        switch playerStatus {
        case .idle: break // ignore because we're in between two states
        case .loading: state = .loading(clip)
        case .playing: state = .playing(clip)
        case .paused: state = .paused(clip)
        }
    }

    public func audioClipPlayer(_ player: AudioClipPlayer, didFailPlaying clip: AudioClip, withError error: any Error) {
        log(.error, "didFailPlaying \(clip.link.href): \(error)")
        delegate?.navigator(self, didFailWithError: error)
    }
}
