name: TestApp
options:
  bundleIdPrefix: org.readium
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.9.23
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 5.15.8
  MBProgressHUD:
    url: https://github.com/jdg/MBProgressHUD.git
    from: 1.2.0
targets:
  TestApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: 
      - path: Sources
        excludes:
          - Resources/Fonts
      - path: Sources/Resources/Fonts
        type: folder
    dependencies:
      - framework: Carthage/Build/CryptoSwift.xcframework
      - framework: Carthage/Build/DifferenceKit.xcframework
      - framework: Carthage/Build/Fuzi.xcframework
      - framework: Carthage/Build/Minizip.xcframework
      - framework: Carthage/Build/R2Navigator.xcframework
      - framework: Carthage/Build/R2Shared.xcframework
      - framework: Carthage/Build/R2Streamer.xcframework
      - framework: Carthage/Build/ReadiumAdapterGCDWebServer.xcframework
      - framework: Carthage/Build/ReadiumGCDWebServer.xcframework
      - framework: Carthage/Build/ReadiumInternal.xcframework
      - framework: Carthage/Build/ReadiumOPDS.xcframework
      - framework: Carthage/Build/SwiftSoup.xcframework
      - package: GRDB
      - package: Kingfisher
      - package: MBProgressHUD
    settings:
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)/Carthage
      DEVELOPMENT_TEAM: ${RD_DEVELOPMENT_TEAM}

