name: R2TestApp
options:
  bundleIdPrefix: org.readium
packages:
  R2Shared:
    url: https://github.com/readium/r2-shared-swift.git
    branch: develop
  R2Streamer:
    url: https://github.com/readium/r2-streamer-swift.git
    branch: develop
  R2Navigator:
    url: https://github.com/readium/r2-navigator-swift.git
    branch: develop
  ReadiumOPDS:
    url: https://github.com/readium/r2-opds-swift.git
    branch: develop
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 5.8.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 5.15.8
  MBProgressHUD:
    url: https://github.com/jdg/MBProgressHUD.git
    from: 1.2.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.3.2
targets:
  R2TestApp:
    type: application
    platform: iOS
    deploymentTarget: "13.6"
    sources: 
      - path: Sources
        excludes:
          - Resources/Samples
      - path: Sources/Resources/Samples
        type: folder
    dependencies:
      - package: R2Shared
      - package: R2Streamer
      - package: R2Navigator
      - package: ReadiumOPDS
      - package: GRDB
      - package: Kingfisher
      - package: MBProgressHUD

