name: TestApp
options:
  bundleIdPrefix: org.readium
targets:
  TestApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: 
      - path: Sources
        excludes:
          - Resources/Fonts
      - path: Sources/Resources/Fonts
        type: folder
    settings:
      DEVELOPMENT_TEAM: ${RD_DEVELOPMENT_TEAM}
