name: TestApp
options:
  bundleIdPrefix: org.readium
targets:
  TestApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: 
      - path: Sources
    settings:
      DEVELOPMENT_TEAM: ${RD_DEVELOPMENT_TEAM}
