#!/usr/bin/env python3
"""Generates the accessible name & description sample publication.

Reads `cases.toml` — the single source of truth for the accname test cases —
and writes:

  Tests/SharedTests/Fixtures/Publication/Services/Content/accname/  XHTML
  Sources/Navigator/EPUB/Scripts/test/fixtures/accname/             XHTML
  scripts/accname-sample/accname.epub                               the sample

Standard library only: run it with `python3 generate.py`.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tomllib
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
ASSETS = HERE / "assets"

SWIFT_FIXTURES_DIR = REPO / "Tests/SharedTests/Fixtures/Publication/Services/Content/accname"
JS_FIXTURES_DIR = REPO / "Sources/Navigator/EPUB/Scripts/test/fixtures/accname"
EPUB_PATH = HERE / "accname.epub"

GENERATED_BY = "Generated by scripts/accname-sample/generate.py — do not edit."

# Publication identity. Fixed so that regenerating produces byte-identical
# output when the manifest has not changed.
PUBLICATION_ID = "urn:uuid:6f1f4d0e-2c2a-4a3f-9d1e-1a2b3c4d5e6f"
MODIFIED = "2026-01-01T00:00:00Z"

ASSET_MEDIA_TYPES = {
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".m4a": "audio/mp4",
    ".mp4": "video/mp4",
}


class ValidationError(Exception):
    """A manifest or generated-document problem that must fail the run."""


# Manifest

@dataclass
class Case:
    id: str
    title: str
    markup: str
    name: str | None = None
    description: str | None = None
    caption: str | None = None
    # Expected extended description links, as a list of {"href", "title"}
    # tables. Absent means "expected none"; hrefs are relative to the document.
    extended_descriptions: list | None = None
    note: str | None = None
    divergence: str | None = None
    skipped: bool = False


@dataclass
class Resource:
    id: str
    title: str
    intro: str
    cases: list[Case] = field(default_factory=list)

    @property
    def filename(self) -> str:
        return f"{self.id}.xhtml"


CASE_KEYS = {
    "id",
    "title",
    "markup",
    "name",
    "description",
    "caption",
    "extended_descriptions",
    "note",
    "divergence",
    "skipped",
}
RESOURCE_KEYS = {"id", "title", "intro", "case"}


def load_manifest(path: Path) -> list[Resource]:
    manifest = tomllib.loads(path.read_text(encoding="utf-8"))
    resources = []
    for entry in manifest.get("resource", []):
        unknown = set(entry) - RESOURCE_KEYS
        if unknown:
            raise ValidationError(f"unknown resource keys {sorted(unknown)}")
        cases = []
        for raw in entry.get("case", []):
            unknown = set(raw) - CASE_KEYS
            if unknown:
                raise ValidationError(
                    f"case '{raw.get('id')}': unknown keys {sorted(unknown)}"
                )
            cases.append(Case(**raw))
        resources.append(
            Resource(
                id=entry["id"],
                title=entry["title"],
                intro=entry["intro"].strip(),
                cases=cases,
            )
        )
    return resources


# XHTML rendering

def escape_text(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def escape_attr(value: str) -> str:
    return escape_text(value).replace('"', "&quot;")


def prose(text: str) -> str:
    """Escapes `text` and turns `backtick` spans into <code> elements."""
    parts = escape_text(" ".join(text.split())).split("`")
    if len(parts) % 2 == 0:
        raise ValidationError(f"unbalanced backticks in: {text}")
    return "".join(
        part if index % 2 == 0 else f"<code>{part}</code>"
        for index, part in enumerate(parts)
    )


def expected_extended_descriptions_json(case: Case) -> str:
    """Serializes the expected extended descriptions as a JSON array of
    `{"href", "title"}` objects. JSON survives attribute escaping, unlike
    separator formats which break on real titles."""
    links = []
    for link in case.extended_descriptions or []:
        unknown = set(link) - {"href", "title"}
        if unknown or "href" not in link:
            raise ValidationError(
                f"case '{case.id}': extended description entries need an "
                f"'href' and an optional 'title', got {sorted(link)}"
            )
        links.append({"href": link["href"], "title": link.get("title")})
    return json.dumps(links, ensure_ascii=False)


def subject_attributes(case: Case) -> str:
    attributes = [f'id="case-{case.id}"', f'data-case="{case.id}"']
    if case.name is not None:
        attributes.append(f'data-expected-name="{escape_attr(case.name)}"')
    if case.description is not None:
        attributes.append(
            f'data-expected-description="{escape_attr(case.description)}"'
        )
    if case.caption is not None:
        attributes.append(f'data-expected-caption="{escape_attr(case.caption)}"')
    if case.extended_descriptions is not None:
        attributes.append(
            "data-expected-extended-descriptions="
            f'"{escape_attr(expected_extended_descriptions_json(case))}"'
        )
    if case.skipped:
        attributes.append('data-test-skipped=""')
    return " ".join(attributes)


MARKER = 'data-subject=""'


def render_markup(case: Case) -> str:
    if case.markup.count(MARKER) != 1:
        raise ValidationError(
            f"case '{case.id}': expected exactly one {MARKER} marker, "
            f"found {case.markup.count(MARKER)}"
        )
    return case.markup.replace(MARKER, subject_attributes(case)).strip("\n")


def render_expectation(value: str | None) -> str:
    if value is None:
        return '<dd class="none">none</dd>'
    return f"<dd><code>{escape_text(value)}</code></dd>"


def render_extended_descriptions(case: Case) -> str:
    if not case.extended_descriptions:
        return '<dd class="none">none</dd>'
    return "".join(
        f'<dd><code>{escape_text(link["href"])}</code>'
        + (f', titled “{escape_text(link["title"])}”' if link.get("title") else "")
        + "</dd>"
        for link in case.extended_descriptions
    )


def render_case(case: Case) -> str:
    lines = [
        f'<section class="case" id="section-{case.id}">',
        f"  <h2>{prose(case.title)}</h2>",
        '  <dl class="expect">',
        f"    <dt>Name</dt>{render_expectation(case.name)}",
        f"    <dt>Description</dt>{render_expectation(case.description)}",
        # Rendered unconditionally: absent means "expected none", so a
        # proofreader must be able to tell that from "captions are not part of
        # this case".
        f"    <dt>Caption</dt>{render_expectation(case.caption)}",
    ]
    if case.extended_descriptions is not None:
        lines.append(
            "    <dt>Extended descriptions</dt>"
            + render_extended_descriptions(case)
        )
    lines.append("  </dl>")
    if case.skipped:
        lines.append(
            '  <p class="skipped">Not implemented yet: neither test harness '
            "asserts this case.</p>"
        )
    if case.note:
        lines.append(f'  <p class="note">{prose(case.note)}</p>')
    if case.divergence:
        lines.append(
            f'  <p class="divergence">Divergence: {prose(case.divergence)}</p>'
        )
    lines.append('  <div class="subject">')
    lines.extend(f"    {line}" for line in render_markup(case).split("\n"))
    lines.append("  </div>")
    lines.append("</section>")
    return "\n".join(lines)


def render_document(resource: Resource) -> str:
    sections = "\n\n".join(render_case(case) for case in resource.cases)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED_BY} -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en" xml:lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{escape_text(resource.title)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
<h1>{escape_text(resource.title)}</h1>
<p class="intro">{prose(resource.intro)}</p>

{sections}
</body>
</html>
"""


def render_nav(resources: list[Resource]) -> str:
    items = "\n".join(
        f'      <li><a href="{resource.filename}">{escape_text(resource.title)}</a></li>'
        for resource in resources
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED_BY} -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en" xml:lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Table of Contents</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
<h1>Accessible name &amp; description</h1>
<nav epub:type="toc" id="toc">
  <h2>Table of Contents</h2>
  <ol>
{items}
  </ol>
</nav>
</body>
</html>
"""


def render_package(resources: list[Resource], assets: list[str]) -> str:
    manifest_items = [
        '    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>',
        '    <item id="styles" href="styles.css" media-type="text/css"/>',
    ]
    for resource in resources:
        # EPUB 3 requires the `svg` property on documents embedding an inline
        # SVG. An SVG behind an `img` does not count.
        inline_svg = any("<svg" in case.markup for case in resource.cases)
        properties = ' properties="svg"' if inline_svg else ""
        manifest_items.append(
            f'    <item id="{resource.id}" href="{resource.filename}" '
            f'media-type="application/xhtml+xml"{properties}/>'
        )
    for index, asset in enumerate(sorted(assets)):
        media_type = ASSET_MEDIA_TYPES[Path(asset).suffix]
        manifest_items.append(
            f'    <item id="asset{index}" href="assets/{asset}" '
            f'media-type="{media_type}"/>'
        )
    spine_items = "\n".join(
        f'    <itemref idref="{resource.id}"/>' for resource in resources
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED_BY} -->
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id" xml:lang="en">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="pub-id">{PUBLICATION_ID}</dc:identifier>
    <dc:title>Accessible name &amp; description</dc:title>
    <dc:language>en</dc:language>
    <dc:creator>Readium Foundation</dc:creator>
    <meta property="dcterms:modified">{MODIFIED}</meta>
  </metadata>
  <manifest>
{chr(10).join(manifest_items)}
  </manifest>
  <spine>
    <itemref idref="nav"/>
{spine_items}
  </spine>
</package>
"""


CONTAINER_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED_BY} -->
<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0">
  <rootfiles>
    <rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"""

STYLES_CSS = f"""/* {GENERATED_BY} */

body {{
  font-family: -apple-system, system-ui, sans-serif;
  line-height: 1.5;
  margin: 1em;
}}

h1 {{
  font-size: 1.5em;
}}

.intro {{
  color: #444;
}}

.case {{
  border-top: 1px solid #ddd;
  margin-top: 2em;
  padding-top: 0.5em;
}}

.case h2 {{
  font-size: 1.1em;
}}

code {{
  font-family: ui-monospace, monospace;
  font-size: 0.9em;
  background: #f2f2f2;
  padding: 0 0.2em;
}}

.expect {{
  background: #f7f7f7;
  border-left: 3px solid #999;
  margin: 0.5em 0;
  padding: 0.5em 0.8em;
}}

.expect dt {{
  font-weight: bold;
  font-size: 0.85em;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #555;
}}

.expect dd {{
  margin: 0 0 0.4em 0;
}}

.expect dd.none {{
  color: #888;
  font-style: italic;
}}

.note {{
  color: #444;
  font-size: 0.9em;
}}

.divergence {{
  background: #fff6e0;
  border-left: 3px solid #e0a800;
  padding: 0.4em 0.8em;
  font-size: 0.9em;
}}

.skipped {{
  background: #f0f0f0;
  border-left: 3px solid #999;
  padding: 0.4em 0.8em;
  font-size: 0.9em;
}}

.subject {{
  border: 1px dashed #bbb;
  padding: 0.8em;
}}

.subject img, .subject svg, .subject video {{
  max-width: 100%;
}}

table {{
  border-collapse: collapse;
}}

th, td {{
  border: 1px solid #999;
  padding: 0.2em 0.5em;
}}
"""


# Validation

XHTML = "{http://www.w3.org/1999/xhtml}"


def validate(documents: dict[str, str], resources: list[Resource], files: set[str]):
    """Fails the run on a malformed document, a duplicate id or a dangling link.

    `files` holds every path packaged under `EPUB/`, relative to that folder.
    """
    seen_cases: set[str] = set()
    for resource in resources:
        for case in resource.cases:
            if case.id in seen_cases:
                raise ValidationError(f"duplicate case id '{case.id}'")
            seen_cases.add(case.id)

    for filename, content in documents.items():
        try:
            root = ElementTree.fromstring(content)
        except ElementTree.ParseError as error:
            raise ValidationError(f"{filename}: not well-formed XML: {error}")

        ids: set[str] = set()
        for element in root.iter():
            identifier = element.get("id")
            if identifier is not None:
                if identifier in ids:
                    raise ValidationError(
                        f"{filename}: duplicate element id '{identifier}'"
                    )
                ids.add(identifier)

            for attribute in ("src", "href"):
                link = element.get(attribute)
                if link is None:
                    continue
                if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", link):
                    # Any absolute URL: http(s), but also the mailto: links
                    # some cases use to pin the scheme filtering down.
                    continue
                # Resolve the same way a reading system would: drop the
                # fragment, then the `./` prefix some cases use to pin down
                # href normalization.
                target = link.split("#", 1)[0].removeprefix("./")
                if target == "":
                    # Empty and fragment-only links stay inside the document;
                    # some cases use them deliberately.
                    continue
                if target not in files:
                    raise ValidationError(
                        f"{filename}: {attribute}=\"{link}\" does not resolve "
                        "to a packaged file"
                    )




def write_fixtures(directory: Path, documents: dict[str, str]):
    """Replaces `directory` with the generated XHTML.

    The directory is wiped first so that renaming a resource in the manifest
    does not leave a stale document behind for a test suite to pick up.
    """
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True)
    for filename, content in documents.items():
        (directory / filename).write_text(content, encoding="utf-8")


def write_epub(members: dict[str, str], assets: list[str]):
    """Writes the EPUB straight to a zip, with no exploded copy on disk.

    Entry timestamps are fixed, so regenerating an unchanged manifest produces
    a byte-identical archive and no diff noise.
    """
    with zipfile.ZipFile(EPUB_PATH, "w") as archive:

        def add(name: str, data: bytes, compress: int = zipfile.ZIP_DEFLATED):
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = compress
            archive.writestr(info, data)

        # The mimetype entry must come first and be stored uncompressed.
        add("mimetype", b"application/epub+zip", zipfile.ZIP_STORED)

        for name in sorted(members):
            add(name, members[name].encode("utf-8"))
        for asset in assets:
            add(f"EPUB/assets/{asset}", (ASSETS / asset).read_bytes())


# epubcheck

BASELINE_PATH = HERE / "epubcheck-baseline.txt"

MESSAGE_PATTERN = re.compile(
    r"^(ERROR|WARNING)\(([A-Z]+-\d+)\): (?:\S*/)?(\S+?)\([-\d]+,[-\d]+\): (.*)$"
)


def run_epubcheck(update_baseline: bool) -> int:
    """Diffs epubcheck's output against the committed baseline.

    Several cases pin down how we handle markup that is *deliberately*
    malformed — dangling IDREFs, uppercase ARIA values, `role` token lists — so
    the sample cannot be epubcheck-clean without dropping the behaviour it
    exists to document. The baseline keeps the check meaningful anyway: any
    message that is not already accounted for fails the run.

    Line and column numbers are dropped so that reordering or re-wording a case
    does not churn the baseline.
    """
    if shutil.which("epubcheck") is None:
        print("epubcheck not on the PATH, skipping validation.")
        return 0

    output = subprocess.run(
        ["epubcheck", str(EPUB_PATH)], capture_output=True, text=True
    )
    found = sorted(
        f"{match.group(1)}({match.group(2)}) {match.group(3)}: {match.group(4)}"
        for line in (output.stdout + output.stderr).splitlines()
        if (match := MESSAGE_PATTERN.match(line.strip()))
    )

    if update_baseline:
        BASELINE_PATH.write_text(
            "# Expected epubcheck messages, one per deliberately invalid case.\n"
            "# Refresh with `python3 generate.py --update-epubcheck-baseline`.\n"
            + "".join(f"{message}\n" for message in found),
            encoding="utf-8",
        )
        print(f"Wrote {len(found)} expected epubcheck messages to the baseline.")
        return 0

    expected = sorted(
        line
        for line in BASELINE_PATH.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    )
    if found == expected:
        print(f"epubcheck: {len(found)} expected messages, no new ones.")
        return 0

    for message in sorted(set(found) - set(expected)):
        print(f"error: unexpected epubcheck message: {message}", file=sys.stderr)
    for message in sorted(set(expected) - set(found)):
        print(f"error: baselined epubcheck message no longer reported: {message}", file=sys.stderr)
    print(
        "Fix the markup, or refresh the baseline with "
        "`make accname-sample-baseline`.",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    resources = load_manifest(HERE / "cases.toml")
    assets = sorted(path.name for path in ASSETS.iterdir() if path.is_file())

    documents = {
        resource.filename: render_document(resource) for resource in resources
    }
    nav = render_nav(resources)

    members = {
        "META-INF/container.xml": CONTAINER_XML,
        "EPUB/package.opf": render_package(resources, assets),
        "EPUB/nav.xhtml": nav,
        "EPUB/styles.css": STYLES_CSS,
        **{f"EPUB/{name}": content for name, content in documents.items()},
    }

    files = {name[len("EPUB/") :] for name in members if name.startswith("EPUB/")}
    files |= {f"assets/{asset}" for asset in assets}

    try:
        validate({**documents, "nav.xhtml": nav}, resources, files)
    except ValidationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    write_fixtures(SWIFT_FIXTURES_DIR, documents)
    write_fixtures(JS_FIXTURES_DIR, documents)
    write_epub(members, assets)

    total = sum(len(resource.cases) for resource in resources)
    skipped = sum(
        1 for resource in resources for case in resource.cases if case.skipped
    )
    print(
        f"Wrote {len(documents)} documents, {total} cases "
        f"({skipped} skipped) to:\n"
        f"  {SWIFT_FIXTURES_DIR.relative_to(REPO)}\n"
        f"  {JS_FIXTURES_DIR.relative_to(REPO)}\n"
        f"  {EPUB_PATH.relative_to(REPO)}"
    )

    return run_epubcheck(update_baseline="--update-epubcheck-baseline" in sys.argv)


if __name__ == "__main__":
    sys.exit(main())
