//
//  Copyright 2026 Readium Foundation. All rights reserved.
//  Use of this source code is governed by the BSD-style license
//  available in the top-level LICENSE file of the project.
//

import Foundation
import ReadiumShared
@testable import ReadiumStreamer
import Testing

/// The fixtures are generated by `Fixtures/audio/generate.sh`, which holds
/// their tags.
enum DefaultAudioMetadataReaderTests {
    struct MP4 {
        /// `faststart.m4b` holds its metadata at the start of the file.
        @Test(arguments: ["tagged.m4b", "faststart.m4b"])
        func readsTheAtoms(fixture: String) async throws {
            #expect(try await reader.read(fixture: fixture) == AudioMetadata(
                title: "Part One",
                album: "The Book",
                // In `tagged.m4b`, `©st3` is blank and the subtitle comes from
                // `----:SUBTITLE`. In `faststart.m4b`, it comes from `©st3`,
                // which has priority over another `----:SUBTITLE`.
                subtitle: "A Subtitle",
                // An MP4 value is not split on `/`.
                albumArtists: ["Jane Author/Jill Author"],
                artists: ["Jane Author/Jill Author", "Nora Narrator"],
                narrators: ["Nora Narrator/Ned Narrator"],
                composers: ["Carl Composer/Cleo Composer"],
                movementName: "The Movement",
                movementIndex: 3,
                // From `----:series`, after a `SERIES` atom with another mean.
                series: "The Saga",
                seriesPosition: 2.5,
                publishers: ["Acme Audio/Books"],
                date: "2021-03-04".dateFromISO8601,
                genres: ["Fantasy", "Adventure"],
                description: "A long description.",
                summary: "A summary.",
                comment: "A comment.",
                // The second value, `eng/deu`, is not a language.
                languages: ["fr"],
                isbn: "978-1-234-56789-7",
                sortAlbum: "Saga 2 - The Book",
                sortTitle: "Part 1",
                cover: Cover(data: fixtures.data(at: "cover.jpg"), mediaType: .jpeg),
                duration: 3,
                bitrate: 32,
                // From the chapter track. The Nero atom holds another title.
                chapters: [
                    Chapter(title: "Opening", start: 0, duration: 1),
                    Chapter(title: "Chapitre deux é", start: 1, duration: 1.5),
                    Chapter(start: 2.5, duration: 0.5),
                ]
            ))
        }

        @Test func readsTheNeroChaptersWithoutAChapterTrack() async throws {
            #expect(try await reader.read(fixture: "nero.m4b") == AudioMetadata(
                duration: 3,
                bitrate: 32,
                chapters: [
                    Chapter(title: "One", start: 0, duration: 1.5),
                    Chapter(title: "Two", start: 1.5, duration: 1.5),
                ]
            ))
        }
    }

    struct ID3 {
        @Test func readsTheID3v24Frames() async throws {
            #expect(try await reader.read(fixture: "tagged.mp3") == AudioMetadata(
                title: "Part 2",
                album: "The Book",
                subtitle: "A Subtitle",
                albumArtists: ["Jane Author"],
                // Only the first of the two values of the frame.
                artists: ["Jane Author"],
                narrators: ["Nora Narrator", "Ned Narrator"],
                composers: ["Carl Composer"],
                // No movement: `MVNM` and `MVIN` are not read.
                series: "The Saga",
                seriesPosition: 2.5,
                publishers: ["Acme Audio"],
                releaseDate: "2021-03-04".dateFromISO8601,
                // From `TDRC`, which has priority over `TYER`.
                date: "2020-01-02T10:20:00Z".dateFromISO8601,
                genres: ["Fantasy", "Adventure"],
                description: "A long description.",
                summary: "A summary.",
                // The `COMM` frame without a description, which follows a
                // technical one.
                comment: "A comment following the technical comment.",
                languages: ["fr", "en"],
                isbn: "9781234567897",
                sortAlbum: "Saga 2 - The Book",
                sortTitle: "Part 2",
                // The embedded front cover, which follows a linked front cover
                // and a back cover.
                cover: Cover(data: fixtures.data(at: "cover.png"), mediaType: .png),
                duration: 3,
                bitrate: 32,
                // The file lists them in another order.
                chapters: [
                    Chapter(title: "Opening", start: 0, duration: 1),
                    Chapter(title: "Chapitre deux é", start: 1, duration: 1.5),
                    Chapter(start: 2.5, duration: 0.5),
                ]
            ))
        }

        @Test func readsTheID3v23Frames() async throws {
            #expect(try await reader.read(fixture: "tagged-v23.mp3") == AudioMetadata(
                title: "Part 3",
                albumArtists: ["Jane Author", "Jill Author"],
                artists: ["Jane Author", "Nora Narrator"],
                composers: ["Nora Narrator", "Ned Narrator"],
                publishers: ["Acme Audio", "Other Press"],
                // From `TYER`.
                date: "2021".dateFromISO8601,
                genres: ["Fantasy"],
                languages: ["en", "fr"],
                // The only picture, which is not a front cover and is
                // declared as `image/jpg`.
                cover: Cover(data: fixtures.data(at: "cover.jpg"), mediaType: .jpeg),
                duration: 3,
                bitrate: 32
            ))
        }

        @Test func bitrateIsUnknownWithoutAXingHeader() async throws {
            #expect(try await reader.read(fixture: "noxing.mp3") == AudioMetadata(duration: 3))
        }

        /// AVFoundation gives no chapter when a `CTOC` frame lists another
        /// one.
        @Test func readsNoChapterOfANestedTableOfContents() async throws {
            #expect(try await reader.read(fixture: "nested-toc.mp3") == AudioMetadata(
                title: "Nested",
                duration: 3,
                bitrate: 32
            ))
        }
    }

    struct Untagged {
        @Test func readsTheDurationOnly() async throws {
            #expect(try await reader.read(fixture: "untagged.wav") == AudioMetadata(duration: 1))
        }
    }

    struct WithoutCover {
        @Test func readsEverythingButTheCover() async throws {
            var expected = try await reader.read(fixture: "tagged.m4b")
            try #require(expected.cover != nil)
            expected.cover = nil

            #expect(try await reader.read(fixture: "tagged.m4b", includesCover: false) == expected)
        }
    }

    struct Failures {
        /// Ogg is no example of a format which AVFoundation does not declare:
        /// iOS 27 declares it, and reads the Ogg files holding Opus audio.
        @Test(arguments: [
            (Format.mp3, ReadFailure.decoding),
            (Format.webm, ReadFailure.resourceNotSupported),
            (Format.null, ReadFailure.resourceNotSupported),
        ])
        func defectiveFileFailsWithDecodingOnlyForAFormatDeclaredByAVFoundation(format: Format, expected: ReadFailure) async {
            let result = await reader.read(AudioMetadataRequest(fixture: "garbage.mp3", format: format))

            #expect(result.readFailure == expected)
        }

        @Test func missingFileFailsWithAnAccessError() async {
            let result = await reader.read(AudioMetadataRequest(fixture: "missing.mp3"))

            #expect(result.readFailure == .fileNotFound)
        }

        @Test func resourceInMemoryIsNotSupported() async {
            let result = await reader.read(AudioMetadataRequest(
                resource: DataResource(data: fixtures.data(at: "tagged.mp3")),
                format: .mp3
            ))

            #expect(result.readFailure == .resourceNotSupported)
        }

        @Test func entryOfAZIPArchiveIsNotSupported() async throws {
            let container = try await ZIPArchiveOpener().open(
                resource: FileResource(file: Fixtures().url(for: "audiotest.zab")),
                format: Format(specifications: .zip, .informalAudiobook, mediaType: .zab, fileExtension: "zab")
            ).get().container
            let entry = try #require(container[AnyURL(string: "Test%20Audiobook/Latin.mp3")!])

            let result = await reader.read(AudioMetadataRequest(resource: entry, format: .mp3))

            #expect(result.readFailure == .resourceNotSupported)
        }

        @Test func cancelledTaskFailsWithCancelled() async {
            let task = Task {
                withUnsafeCurrentTask { $0?.cancel() }
                return await reader.read(AudioMetadataRequest(fixture: "tagged.m4b"))
            }

            #expect(await task.value.readFailure == .cancelled)
        }
    }

    /// A failure of the reader without its underlying error, to compare it.
    enum ReadFailure: Equatable {
        case resourceNotSupported
        case decoding
        case fileNotFound
        case cancelled
        case other(String)
    }
}

// MARK: - Helpers

private typealias Chapter = AudioMetadata.Chapter
private typealias Cover = AudioMetadata.Cover
private typealias ReadFailure = DefaultAudioMetadataReaderTests.ReadFailure

private let reader = DefaultAudioMetadataReader()
private let fixtures = Fixtures(path: "audio")

private extension DefaultAudioMetadataReader {
    /// Reads the given audio fixture, then rounds the durations to a tenth of
    /// a second and the bitrate to a kbps.
    ///
    /// The durations of the fixtures depend on their encoding: a file of
    /// three seconds reports from 2.98 to 3.03 seconds.
    func read(fixture: String, includesCover: Bool = true) async throws -> AudioMetadata {
        var metadata = try await read(AudioMetadataRequest(fixture: fixture, includesCover: includesCover)).get()
        metadata.duration = metadata.duration?.roundedToTenth
        metadata.bitrate = metadata.bitrate?.rounded()
        metadata.chapters = metadata.chapters.map { chapter in
            var chapter = chapter
            chapter.start = chapter.start.roundedToTenth
            chapter.duration = chapter.duration?.roundedToTenth
            return chapter
        }
        return metadata
    }
}

private extension AudioMetadataRequest {
    /// Creates a request to read the given audio fixture.
    ///
    /// The format only matters when the reading fails.
    init(fixture: String, format: Format = .null, includesCover: Bool = true) {
        self.init(
            resource: FileResource(file: fixtures.url(for: fixture)),
            format: format,
            includesCover: includesCover
        )
    }
}

private extension Format {
    static let mp3 = Format(specifications: .mp3, mediaType: .mp3, fileExtension: "mp3")
    static let webm = Format(specifications: .webm, mediaType: .webmAudio, fileExtension: "webm")
}

private extension Result<AudioMetadata, AudioMetadataReadError> {
    var readFailure: ReadFailure? {
        switch self {
        case .success: nil
        case .failure(.resourceNotSupported): .resourceNotSupported
        case .failure(.reading(.decoding)): .decoding
        case .failure(.reading(.access(.fileSystem(.fileNotFound)))): .fileNotFound
        case .failure(.reading(.cancelled)): .cancelled
        case let .failure(error): .other(String(describing: error))
        }
    }
}

private extension Double {
    var roundedToTenth: Double {
        (self * 10).rounded() / 10
    }
}
