//
//  Copyright 2026 Readium Foundation. All rights reserved.
//  Use of this source code is governed by the BSD-style license
//  available in the top-level LICENSE file of the project.
//

import Foundation
import ReadiumShared

final class DeviceService: Loggable {
    private let repository: LCPLicenseRepository
    private let httpClient: HTTPClient

    /// Returns the device's name.
    let name: String

    /// The device's ID, or `nil` when it could not be resolved.
    ///
    /// The auto-generated ID is `nil` only when the Keychain is temporarily
    /// inaccessible (e.g. before the device's first unlock after a reboot). In
    /// that case we deliberately avoid minting a throwaway ID: registering with
    /// it would burn one of the license's device slots and the ID would change
    /// on the next launch. Callers skip the LSD device interactions until a
    /// later launch resolves the persisted ID.
    let id: String?

    /// Legacy `UserDefaults` key used to persist the auto-generated device ID
    /// before it was moved to the Keychain.
    static let legacyDeviceIDDefaultsKey = "lcp_device_id"

    /// Keychain account key under which the auto-generated device ID is stored.
    static let deviceIDKeychainAccount = "device-id"

    init(
        deviceName: String,
        deviceId: String?,
        repository: LCPLicenseRepository,
        httpClient: HTTPClient,
        keychainServiceName: String = "org.readium.lcp.device"
    ) {
        name = deviceName

        if let providedId = deviceId {
            // The app supplied its own device ID: use it verbatim and never
            // touch the Keychain.
            id = providedId
        } else {
            id = Self.resolveAutoGeneratedID(
                keychain: Keychain(
                    serviceName: keychainServiceName,
                    synchronizable: false
                )
            )
        }

        self.repository = repository
        self.httpClient = httpClient
    }

    /// Resolves the auto-generated device ID, keeping it stable across app
    /// reinstalls by persisting it in the Keychain.
    ///
    /// Resolution order:
    /// 1. An ID already stored in the Keychain is reused.
    /// 2. Otherwise a legacy ID found in `UserDefaults` is migrated to the
    ///    Keychain (the `UserDefaults` value is left untouched).
    /// 3. Otherwise a new ID is generated and stored in the Keychain.
    ///
    /// Returns `nil` when the Keychain cannot be read (e.g. it is still locked
    /// before the first unlock) or holds an unreadable item: an ID may already
    /// exist there, so we neither mint a new one nor overwrite it. See ``id``.
    private static func resolveAutoGeneratedID(keychain: Keychain) -> String? {
        // 1. Reuse an ID already stored in the Keychain.
        do {
            if let id = try loadID(from: keychain) {
                return id
            }
        } catch {
            // A read failure is not the same as "no ID": an ID may exist but be
            // temporarily unreadable. Minting a new one here would register the
            // device under a throwaway ID and burn a slot.
            log(.error, "Failed to read the LCP device ID from the Keychain: \(error)")
            return nil
        }

        // 2. Migrate a legacy `UserDefaults` ID, or 3. generate a new one.
        let legacyID = UserDefaults.standard.string(forKey: legacyDeviceIDDefaultsKey)
        let id = legacyID ?? UUID().uuidString

        do {
            try keychain.save(data: Data(id.utf8), forKey: deviceIDKeychainAccount)
            return id
        } catch .duplicateItem {
            // Another instance stored an ID between our read and write, or an
            // existing item was unreadable above. Re-read so we return the
            // stored ID rather than a conflicting fresh one; if it is still
            // unreadable, report "no ID" rather than a throwaway.
            return try? loadID(from: keychain)
        } catch {
            log(.error, "Failed to persist the LCP device ID in the Keychain: \(error)")
            // A legacy ID is still persisted in `UserDefaults`, so it stays
            // stable across launches even without the Keychain and is safe to
            // use. A freshly generated ID exists only in memory: using it would
            // register a throwaway that changes next launch and burns a slot, so
            // report "no ID" instead.
            return legacyID
        }
    }

    /// Loads the stored device ID from the Keychain, or `nil` if none is stored.
    ///
    /// Throws when the Keychain is inaccessible or the stored bytes are not
    /// valid UTF-8, so an unreadable item is never mistaken for an absent one.
    private static func loadID(from keychain: Keychain) throws(KeychainError) -> String? {
        guard let data = try keychain.load(forKey: deviceIDKeychainAccount) else {
            return nil
        }
        guard let id = String(data: data, encoding: .utf8) else {
            throw .invalidData
        }
        return id
    }

    /// Device ID and name as query parameters for HTTP requests, or `nil` when
    /// the device ID could not be resolved (see ``id``).
    var asQueryParameters: [String: String]? {
        guard let id else {
            return nil
        }
        return [
            "id": id,
            "name": name,
        ]
    }

    /// Registers the device for the given license.
    /// If the call was made, the updated Status Document data is given to the completion closure.
    @discardableResult
    func registerLicense(_ license: LicenseDocument, at link: Link) async throws -> Data? {
        let registered = try await repository.isDeviceRegistered(for: license.id)
        guard !registered else {
            return nil
        }
        guard let parameters = asQueryParameters else {
            // The device ID is temporarily unavailable (e.g. the Keychain is
            // locked before the first unlock). Skip registration; a later
            // launch will register once the ID resolves.
            return nil
        }
        guard let url = link.url(parameters: parameters) else {
            throw LCPError.licenseInteractionNotAvailable
        }

        let data = await httpClient.fetch(HTTPRequest(url: url, method: .post))
            .map(\.body)

        try await repository.registerDevice(for: license.id)

        return try data.get()
    }
}
