name: Readium
attributes:
  LastUpgradeCheck: "1250"
options:
  bundleIdPrefix: org.readium

targets:

  R2Shared:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: ../Sources/Shared
        excludes:
          - Toolkit/Archive/ZIPFoundation.swift
    dependencies:
      - framework: Build/Fuzi.xcframework
      - framework: Build/Minizip.xcframework
      - framework: Build/SwiftSoup.xcframework
      - sdk: CoreServices.framework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-shared-swift
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)

  R2Streamer:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: ../Sources/Streamer
        excludes:
          - Assets
      - path: ../Sources/Streamer/Assets
        type: folder
    dependencies:
      - framework: Build/CryptoSwift.xcframework
      - framework: Build/Fuzi.xcframework
      - framework: Build/GCDWebServer.xcframework
      - framework: Build/Minizip.xcframework
      - target: R2Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-streamer-swift
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)

  R2Navigator:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: ../Sources/Navigator
        excludes:
          - EPUB/Assets
          - EPUB/Scripts
      - path: ../Sources/Navigator/EPUB/Assets
        type: folder
    dependencies:
      - framework: Build/DifferenceKit.xcframework
      - framework: Build/Fuzi.xcframework
      - framework: Build/Minizip.xcframework
      - framework: Build/SwiftSoup.xcframework
      - target: R2Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-navigator-swift
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)

  ReadiumOPDS:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: ../Sources/OPDS
    dependencies:
      - framework: Build/Fuzi.xcframework
      - framework: Build/Minizip.xcframework
      - target: R2Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.readium.readium-opds
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)

  ReadiumLCP:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: ../Sources/LCP
    dependencies:
      - framework: Build/CryptoSwift.xcframework
      - framework: Build/Fuzi.xcframework
      - framework: Build/Minizip.xcframework
      - framework: Build/SQLite.xcframework
      - framework: Build/ZIPFoundation.xcframework
      - target: R2Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.readium-lcp-swift
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)

schemes:
  R2Shared:
    build:
      targets:
        R2Shared: all
  R2Streamer:
    build:
      targets:
        R2Streamer: all
  R2Navigator:
    build:
      targets:
        R2Navigator: all
  ReadiumOPDS:
    build:
      targets:
        ReadiumOPDS: all
  ReadiumLCP:
    build:
      targets:
        ReadiumLCP: all
