#!/usr/bin/env python3
"""
gen-lcp-testplan.py PLAN OUTPUT PBXPROJ

Writes to OUTPUT a copy of the Playground test plan PLAN with the
ReadiumLCPTests target added.

The other test targets are declared in Package.swift and referenced by name.
ReadiumLCPTests is generated by XcodeGen in the Playground project instead, and
Xcode expects its identifier to be the UUID of the target in the project. It is
resolved from PBXPROJ, which is only available after XcodeGen ran.
"""

import json
import re
import sys

TARGET_NAME = "ReadiumLCPTests"

def identifier(pbxproj_path):
    with open(pbxproj_path) as file:
        contents = file.read()

    match = re.search(
        r"([0-9A-F]{24}) /\* " + TARGET_NAME + r" \*/ = \{\s*isa = PBXNativeTarget;",
        contents,
    )
    if match is None:
        sys.exit("error: target {} not found in {}".format(TARGET_NAME, pbxproj_path))

    return match.group(1)

if len(sys.argv) != 4:
    sys.exit(__doc__.strip())

plan_path, output_path, pbxproj_path = sys.argv[1], sys.argv[2], sys.argv[3]

with open(plan_path) as file:
    plan = json.load(file)

plan["testTargets"].append(
    {
        "target": {
            "containerPath": "container:Playground.xcodeproj",
            "identifier": identifier(pbxproj_path),
            "name": TARGET_NAME,
        }
    }
)

with open(output_path, "w") as file:
    json.dump(plan, file, indent=2)
