//
//  Copyright 2025 Readium Foundation. All rights reserved.
//  Use of this source code is governed by the BSD-style license
//  available in the top-level LICENSE file of the project.
//

// DO NOT EDIT. File generated automatically from v2.0.c of the en-US JSON strings.

public extension AccessibilityDisplayString {
    static let waysOfReadingTitle: Self = "readium.a11y.ways-of-reading-title"
    static let waysOfReadingNonvisualReadingAltText: Self = "readium.a11y.ways-of-reading-nonvisual-reading-alt-text"
    static let waysOfReadingNonvisualReadingNoMetadata: Self = "readium.a11y.ways-of-reading-nonvisual-reading-no-metadata"
    static let waysOfReadingNonvisualReadingNone: Self = "readium.a11y.ways-of-reading-nonvisual-reading-none"
    static let waysOfReadingNonvisualReadingNotFully: Self = "readium.a11y.ways-of-reading-nonvisual-reading-not-fully"
    static let waysOfReadingNonvisualReadingReadable: Self = "readium.a11y.ways-of-reading-nonvisual-reading-readable"
    static let waysOfReadingPrerecordedAudioComplementary: Self = "readium.a11y.ways-of-reading-prerecorded-audio-complementary"
    static let waysOfReadingPrerecordedAudioNoMetadata: Self = "readium.a11y.ways-of-reading-prerecorded-audio-no-metadata"
    static let waysOfReadingPrerecordedAudioOnly: Self = "readium.a11y.ways-of-reading-prerecorded-audio-only"
    static let waysOfReadingPrerecordedAudioSynchronized: Self = "readium.a11y.ways-of-reading-prerecorded-audio-synchronized"
    static let waysOfReadingVisualAdjustmentsModifiable: Self = "readium.a11y.ways-of-reading-visual-adjustments-modifiable"
    static let waysOfReadingVisualAdjustmentsUnknown: Self = "readium.a11y.ways-of-reading-visual-adjustments-unknown"
    static let waysOfReadingVisualAdjustmentsUnmodifiable: Self = "readium.a11y.ways-of-reading-visual-adjustments-unmodifiable"
    static let conformanceTitle: Self = "readium.a11y.conformance-title"
    static let conformanceDetailsTitle: Self = "readium.a11y.conformance-details-title"
    static let conformanceA: Self = "readium.a11y.conformance-a"
    static let conformanceAa: Self = "readium.a11y.conformance-aa"
    static let conformanceAaa: Self = "readium.a11y.conformance-aaa"
    static let conformanceCertifier: Self = "readium.a11y.conformance-certifier"
    static let conformanceCertifierCredentials: Self = "readium.a11y.conformance-certifier-credentials"
    static let conformanceDetailsCertificationInfo: Self = "readium.a11y.conformance-details-certification-info"
    static let conformanceDetailsCertifierReport: Self = "readium.a11y.conformance-details-certifier-report"
    static let conformanceDetailsClaim: Self = "readium.a11y.conformance-details-claim"
    static let conformanceDetailsEpubAccessibility10: Self = "readium.a11y.conformance-details-epub-accessibility-1-0"
    static let conformanceDetailsEpubAccessibility11: Self = "readium.a11y.conformance-details-epub-accessibility-1-1"
    static let conformanceDetailsLevelA: Self = "readium.a11y.conformance-details-level-a"
    static let conformanceDetailsLevelAa: Self = "readium.a11y.conformance-details-level-aa"
    static let conformanceDetailsLevelAaa: Self = "readium.a11y.conformance-details-level-aaa"
    static let conformanceDetailsWcag20: Self = "readium.a11y.conformance-details-wcag-2-0"
    static let conformanceDetailsWcag21: Self = "readium.a11y.conformance-details-wcag-2-1"
    static let conformanceDetailsWcag22: Self = "readium.a11y.conformance-details-wcag-2-2"
    static let conformanceNo: Self = "readium.a11y.conformance-no"
    static let conformanceUnknownStandard: Self = "readium.a11y.conformance-unknown-standard"
    static let navigationTitle: Self = "readium.a11y.navigation-title"
    static let navigationIndex: Self = "readium.a11y.navigation-index"
    static let navigationNoMetadata: Self = "readium.a11y.navigation-no-metadata"
    static let navigationPageNavigation: Self = "readium.a11y.navigation-page-navigation"
    static let navigationStructural: Self = "readium.a11y.navigation-structural"
    static let navigationToc: Self = "readium.a11y.navigation-toc"
    static let richContentTitle: Self = "readium.a11y.rich-content-title"
    static let richContentAccessibleChemistryAsLatex: Self = "readium.a11y.rich-content-accessible-chemistry-as-latex"
    static let richContentAccessibleChemistryAsMathml: Self = "readium.a11y.rich-content-accessible-chemistry-as-mathml"
    static let richContentAccessibleMathAsLatex: Self = "readium.a11y.rich-content-accessible-math-as-latex"
    static let richContentAccessibleMathAsMathml: Self = "readium.a11y.rich-content-accessible-math-as-mathml"
    static let richContentAccessibleMathDescribed: Self = "readium.a11y.rich-content-accessible-math-described"
    static let richContentClosedCaptions: Self = "readium.a11y.rich-content-closed-captions"
    static let richContentExtended: Self = "readium.a11y.rich-content-extended"
    static let richContentOpenCaptions: Self = "readium.a11y.rich-content-open-captions"
    static let richContentTranscript: Self = "readium.a11y.rich-content-transcript"
    static let richContentUnknown: Self = "readium.a11y.rich-content-unknown"
    static let hazardsTitle: Self = "readium.a11y.hazards-title"
    static let hazardsFlashing: Self = "readium.a11y.hazards-flashing"
    static let hazardsFlashingNone: Self = "readium.a11y.hazards-flashing-none"
    static let hazardsFlashingUnknown: Self = "readium.a11y.hazards-flashing-unknown"
    static let hazardsMotion: Self = "readium.a11y.hazards-motion"
    static let hazardsMotionNone: Self = "readium.a11y.hazards-motion-none"
    static let hazardsMotionUnknown: Self = "readium.a11y.hazards-motion-unknown"
    static let hazardsNoMetadata: Self = "readium.a11y.hazards-no-metadata"
    static let hazardsNone: Self = "readium.a11y.hazards-none"
    static let hazardsSound: Self = "readium.a11y.hazards-sound"
    static let hazardsSoundNone: Self = "readium.a11y.hazards-sound-none"
    static let hazardsSoundUnknown: Self = "readium.a11y.hazards-sound-unknown"
    static let hazardsUnknown: Self = "readium.a11y.hazards-unknown"
    static let accessibilitySummaryTitle: Self = "readium.a11y.accessibility-summary-title"
    static let accessibilitySummaryNoMetadata: Self = "readium.a11y.accessibility-summary-no-metadata"
    static let accessibilitySummaryPublisherContact: Self = "readium.a11y.accessibility-summary-publisher-contact"
    static let legalConsiderationsTitle: Self = "readium.a11y.legal-considerations-title"
    static let legalConsiderationsExempt: Self = "readium.a11y.legal-considerations-exempt"
    static let legalConsiderationsNoMetadata: Self = "readium.a11y.legal-considerations-no-metadata"
    static let additionalAccessibilityInformationTitle: Self = "readium.a11y.additional-accessibility-information-title"
    static let additionalAccessibilityInformationAria: Self = "readium.a11y.additional-accessibility-information-aria"
    static let additionalAccessibilityInformationAudioDescriptions: Self = "readium.a11y.additional-accessibility-information-audio-descriptions"
    static let additionalAccessibilityInformationBraille: Self = "readium.a11y.additional-accessibility-information-braille"
    static let additionalAccessibilityInformationColorNotSoleMeansOfConveyingInformation: Self = "readium.a11y.additional-accessibility-information-color-not-sole-means-of-conveying-information"
    static let additionalAccessibilityInformationDyslexiaReadability: Self = "readium.a11y.additional-accessibility-information-dyslexia-readability"
    static let additionalAccessibilityInformationFullRubyAnnotations: Self = "readium.a11y.additional-accessibility-information-full-ruby-annotations"
    static let additionalAccessibilityInformationHighContrastBetweenForegroundAndBackgroundAudio: Self = "readium.a11y.additional-accessibility-information-high-contrast-between-foreground-and-background-audio"
    static let additionalAccessibilityInformationHighContrastBetweenTextAndBackground: Self = "readium.a11y.additional-accessibility-information-high-contrast-between-text-and-background"
    static let additionalAccessibilityInformationLargePrint: Self = "readium.a11y.additional-accessibility-information-large-print"
    static let additionalAccessibilityInformationPageBreaks: Self = "readium.a11y.additional-accessibility-information-page-breaks"
    static let additionalAccessibilityInformationRubyAnnotations: Self = "readium.a11y.additional-accessibility-information-ruby-annotations"
    static let additionalAccessibilityInformationSignLanguage: Self = "readium.a11y.additional-accessibility-information-sign-language"
    static let additionalAccessibilityInformationTactileGraphics: Self = "readium.a11y.additional-accessibility-information-tactile-graphics"
    static let additionalAccessibilityInformationTactileObjects: Self = "readium.a11y.additional-accessibility-information-tactile-objects"
    static let additionalAccessibilityInformationTextToSpeechHinting: Self = "readium.a11y.additional-accessibility-information-text-to-speech-hinting"
    static let additionalAccessibilityInformationUltraHighContrastBetweenTextAndBackground: Self = "readium.a11y.additional-accessibility-information-ultra-high-contrast-between-text-and-background"
    static let additionalAccessibilityInformationVisiblePageNumbering: Self = "readium.a11y.additional-accessibility-information-visible-page-numbering"
    static let additionalAccessibilityInformationWithoutBackgroundSounds: Self = "readium.a11y.additional-accessibility-information-without-background-sounds"
}
