//
//  Copyright 2026 Readium Foundation. All rights reserved.
//  Use of this source code is governed by the BSD-style license
//  available in the top-level LICENSE file of the project.
//

// Generates Support/CocoaPods/*.podspec from the module definitions in Specs.swift.
// Run from the repo root via: swift run --package-path BuildTools GeneratePodspecs

import Foundation

let outputDir = URL(fileURLWithPath: "Support/CocoaPods")

guard FileManager.default.fileExists(atPath: outputDir.path) else {
    fputs("Error: '\(outputDir.path)' not found. Run this tool from the repository root.\n", stderr)
    exit(1)
}

for module in modules {
    let content = render(module)
    let dest = outputDir.appendingPathComponent("\(module.name).podspec")
    do {
        try content.write(to: dest, atomically: true, encoding: .utf8)
        print("Wrote \(module.name).podspec")
    } catch {
        fputs("Error: failed to write \(dest.path): \(error)\n", stderr)
        exit(1)
    }
}

func render(_ m: ModuleSpec) -> String {
    var lines: [String] = []

    lines.append("# This file is generated by `make podspecs`. Do not edit manually.")
    lines.append("# Edit Support/CocoaPods/Specs.swift and run `make podspecs` to regenerate.")
    lines.append("")
    lines.append("Pod::Spec.new do |s|")
    lines.append("")
    lines.append("  s.name          = \"\(m.name)\"")
    lines.append("  s.version       = \"\(version)\"")
    lines.append("  s.license       = \"BSD 3-Clause License\"")
    lines.append("  s.summary       = \"\(m.summary)\"")
    lines.append("  s.homepage      = \"http://readium.github.io\"")
    lines.append("  s.author        = { \"Readium\" => \"contact@readium.org\" }")
    lines.append("  s.source        = { :git => \"https://github.com/readium/swift-toolkit.git\", :tag => s.version }")
    lines.append("  s.requires_arc  = true")

    if !m.resourceBundles.isEmpty {
        // Sort by key for deterministic output.
        let sorted = m.resourceBundles.sorted { $0.key < $1.key }
        lines.append("  s.resource_bundles = {")
        for (bundleName, patterns) in sorted {
            if patterns.count == 1 {
                lines.append("    '\(bundleName)' => ['\(patterns[0])'],")
            } else {
                lines.append("    '\(bundleName)' => [")
                for pattern in patterns {
                    lines.append("      '\(pattern)',")
                }
                lines.append("    ],")
            }
        }
        lines.append("  }")
    }

    lines.append("  s.source_files  = \"\(m.sourcePath)/**/*.{m,h,swift}\"")
    lines.append("  s.swift_version = '\(swiftVersion)'")
    lines.append("  s.platform      = :ios")
    lines.append("  s.ios.deployment_target = \"\(iosTarget)\"")

    if !m.frameworks.isEmpty {
        lines.append("  s.frameworks    = \"\(m.frameworks.joined(separator: "\", \""))\"")
    }

    if !m.libraries.isEmpty {
        let quoted = m.libraries.map { "'\($0)'" }.joined(separator: ", ")
        lines.append("  s.libraries     = \(quoted)")
    }

    if !m.xcconfig.isEmpty {
        let sorted = m.xcconfig.sorted { $0.key < $1.key }
        let pairs = sorted.map { "'\($0.key)' => '\($0.value)'" }.joined(separator: ", ")
        lines.append("  s.xcconfig      = { \(pairs) }")
    }

    if !m.dependencies.isEmpty {
        lines.append("")
        for dep in m.dependencies {
            switch dep {
            case let .readium(name):
                lines.append("  s.dependency '\(name)', '~> \(version)'")
            case let .pod(name, constraint):
                lines.append("  s.dependency '\(name)', '\(constraint)'")
            }
        }
    }

    lines.append("")
    lines.append("end")
    return lines.joined(separator: "\n") + "\n"
}
