name: Readium
attributes:
  LastUpgradeCheck: "1250"
options:
  bundleIdPrefix: org.readium

targets:

  R2Shared:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/Shared
        excludes:
          - Toolkit/Archive/ZIPFoundation.swift
    dependencies:
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/SwiftSoup.xcframework
      - target: ReadiumInternal
      - sdk: CoreServices.framework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-shared-swift
      INFOPLIST_FILE: Info.plist

  R2Streamer:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/Streamer
        excludes:
          - Assets
      - path: ../../Sources/Streamer/Assets
        type: folder
    dependencies:
      - framework: ../../Carthage/Build/CryptoSwift.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/GCDWebServer.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - target: R2Shared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-streamer-swift
      INFOPLIST_FILE: Info.plist

  R2Navigator:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/Navigator
        excludes:
          - EPUB/Assets
          - EPUB/Scripts
      - path: ../../Sources/Navigator/EPUB/Assets
        type: folder
    dependencies:
      - framework: ../../Carthage/Build/DifferenceKit.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/SwiftSoup.xcframework
      - target: R2Shared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.r2-navigator-swift
      INFOPLIST_FILE: Info.plist

  ReadiumOPDS:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/OPDS
    dependencies:
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - target: R2Shared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.readium.readium-opds
      INFOPLIST_FILE: Info.plist

  ReadiumLCP:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/LCP
    dependencies:
      - framework: ../../Carthage/Build/CryptoSwift.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/SQLite.xcframework
      - framework: ../../Carthage/Build/ZIPFoundation.xcframework
      - target: R2Shared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.readium-lcp-swift
      INFOPLIST_FILE: Info.plist

  ReadiumAdapterGCDWebServer:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/Adapters/GCDWebServer
    dependencies:
      - framework: ../../Carthage/Build/GCDWebServer.xcframework
      - target: R2Shared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.adapter.gcdwebserver
      INFOPLIST_FILE: Info.plist

  ReadiumInternal:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: ../../Sources/Internal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.internal
      INFOPLIST_FILE: Info.plist

schemes:
  R2Shared:
    build:
      targets:
        R2Shared: all
  R2Streamer:
    build:
      targets:
        R2Streamer: all
  R2Navigator:
    build:
      targets:
        R2Navigator: all
  ReadiumOPDS:
    build:
      targets:
        ReadiumOPDS: all
  ReadiumLCP:
    build:
      targets:
        ReadiumLCP: all
  ReadiumAdapterGCDWebServer:
    build:
      targets:
        ReadiumAdapterGCDWebServer: all
  ReadiumInternal:
    build:
      targets:
        ReadiumInternal: all
