name: Readium
attributes:
  LastUpgradeCheck: "1250"
options:
  bundleIdPrefix: org.readium

targets:

  ReadiumShared:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Shared
        excludes:
          - Toolkit/Archive/ZIPFoundation.swift
    dependencies:
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/SwiftSoup.xcframework
      - target: ReadiumInternal
      - sdk: CoreServices.framework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.shared
      INFOPLIST_FILE: Info.plist

  ReadiumStreamer:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Streamer
        excludes:
          - Assets
      - path: ../../Sources/Streamer/Assets
        type: folder
    dependencies:
      - framework: ../../Carthage/Build/CryptoSwift.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/ReadiumGCDWebServer.xcframework
      - target: ReadiumShared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.streamer
      INFOPLIST_FILE: Info.plist

  ReadiumNavigator:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Navigator
        excludes:
          - EPUB/Assets
          - EPUB/Scripts
      - path: ../../Sources/Navigator/EPUB/Assets
        type: folder
    dependencies:
      - framework: ../../Carthage/Build/DifferenceKit.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/SwiftSoup.xcframework
      - target: ReadiumShared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.navigator
      INFOPLIST_FILE: Info.plist

  ReadiumOPDS:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/OPDS
    dependencies:
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - target: ReadiumShared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.opds
      INFOPLIST_FILE: Info.plist

  ReadiumLCP:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/LCP
    dependencies:
      - framework: ../../Carthage/Build/CryptoSwift.xcframework
      - framework: ../../Carthage/Build/Fuzi.xcframework
      - framework: ../../Carthage/Build/Minizip.xcframework
      - framework: ../../Carthage/Build/ZIPFoundation.xcframework
      - target: ReadiumShared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.lcp
      INFOPLIST_FILE: Info.plist

  ReadiumAdapterGCDWebServer:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Adapters/GCDWebServer
    dependencies:
      - framework: ../../Carthage/Build/ReadiumGCDWebServer.xcframework
      - target: ReadiumShared
      - target: ReadiumInternal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.adapter.gcdwebserver
      INFOPLIST_FILE: Info.plist

  ReadiumAdapterLCPSQLite:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Adapters/LCPSQLite
    dependencies:
      - framework: ../../Carthage/Build/SQLite.xcframework
      - target: ReadiumShared
      - target: ReadiumLCP
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.adapter.lcpsqlite
      INFOPLIST_FILE: Info.plist

  ReadiumInternal:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      - path: ../../Sources/Internal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.readium.swift-toolkit.internal
      INFOPLIST_FILE: Info.plist

schemes:
  ReadiumShared:
    build:
      targets:
        ReadiumShared: all
  ReadiumStreamer:
    build:
      targets:
        ReadiumStreamer: all
  ReadiumNavigator:
    build:
      targets:
        ReadiumNavigator: all
  ReadiumOPDS:
    build:
      targets:
        ReadiumOPDS: all
  ReadiumLCP:
    build:
      targets:
        ReadiumLCP: all
  ReadiumAdapterGCDWebServer:
    build:
      targets:
        ReadiumAdapterGCDWebServer: all
  ReadiumAdapterLCPSQLite:
    build:
      targets:
        ReadiumAdapterLCPSQLite: all
  ReadiumInternal:
    build:
      targets:
        ReadiumInternal: all
